SET IDENTITY_INSERT medical_center.medical_center.insurance ON;


INSERT INTO medical_center.medical_center.insurance (company_id, company_name, phone_number, percentage, country) VALUES (1,'Aegon Santander Portugal Não Vida - Companhia de Seguros, S.A.', '918077359', '7.022666124', 'Portugal');
INSERT INTO medical_center.medical_center.insurance (company_id, company_name, phone_number, percentage, country) VALUES (2,'Ageas Portugal - Companhia de Seguros, S.A.', '914617832', '6.609387903', 'Portugal');
INSERT INTO medical_center.medical_center.insurance (company_id, company_name, phone_number, percentage, country) VALUES (3,'AIG Europe S.A. - Sucursal em Portugal', '918053807', '2.999945228', 'Luxemburgo');
INSERT INTO medical_center.medical_center.insurance (company_id, company_name, phone_number, percentage, country) VALUES (4,'Asisa, Asistencia Sanitaria Interprovincial de Seguros, S.A.U', '917648608', '1.912746939', 'Espanha');
INSERT INTO medical_center.medical_center.insurance (company_id, company_name, phone_number, percentage, country) VALUES (5,'AWP P&C - Sucursal em Portugal', '911472512', '7.591780463', 'França');
INSERT INTO medical_center.medical_center.insurance (company_id, company_name, phone_number, percentage, country) VALUES (6,'Axa France IARD', '912118117', '3.637680423', 'França');
INSERT INTO medical_center.medical_center.insurance (company_id, company_name, phone_number, percentage, country) VALUES (7,'Axa France Vie', '916360693', '8.500727128', 'França');
INSERT INTO medical_center.medical_center.insurance (company_id, company_name, phone_number, percentage, country) VALUES (8,'Caravela - Companhia de Seguros, S.A.', '912533624', '1.018774335', 'Portugal');
INSERT INTO medical_center.medical_center.insurance (company_id, company_name, phone_number, percentage, country) VALUES (9,'Cardif Assurances Risques Divers', '919070417', '4.577526397', 'França');
INSERT INTO medical_center.medical_center.insurance (company_id, company_name, phone_number, percentage, country) VALUES (10,'Chubb European Group SE ? Sucursal em Portugal', '914153162', '8.750728253', 'França');
INSERT INTO medical_center.medical_center.insurance (company_id, company_name, phone_number, percentage, country) VALUES (11,'Chubb Life Europe SE - Sucursal em Portugal', '917351837', '0.165798987', 'França');
INSERT INTO medical_center.medical_center.insurance (company_id, company_name, phone_number, percentage, country) VALUES (12,'Companhia de Seguros Allianz Portugal, S.A.', '916827610', '3.956317422', 'Portugal');
INSERT INTO medical_center.medical_center.insurance (company_id, company_name, phone_number, percentage, country) VALUES (13,'Companhia Portuguesa de Resseguros, S.A.', '916637808', '7.059484755', 'Portugal');
INSERT INTO medical_center.medical_center.insurance (company_id, company_name, phone_number, percentage, country) VALUES (14,'Crédito Agrícola Seguros - Companhia de Seguros de Ramos Reais, S.A.', '914228319', '3.997124972', 'Portugal');
INSERT INTO medical_center.medical_center.insurance (company_id, company_name, phone_number, percentage, country) VALUES (15,'Fidelidade - Companhia de Seguros, S.A.', '917957542', '3.612842187', 'Portugal');
INSERT INTO medical_center.medical_center.insurance (company_id, company_name, phone_number, percentage, country) VALUES (16,'Generali Seguros, S.A.', '915310300', '8.410746634', 'Portugal');
INSERT INTO medical_center.medical_center.insurance (company_id, company_name, phone_number, percentage, country) VALUES (17,'Hiscox, S.A.', '910266406', '8.880759145', 'Luxemburgo');
INSERT INTO medical_center.medical_center.insurance (company_id, company_name, phone_number, percentage, country) VALUES (18,'Liberty Seguros, Companhia de Seguros Y Reaseguros, S.A.', '918444389', '7.263878947', 'Espanha');
INSERT INTO medical_center.medical_center.insurance (company_id, company_name, phone_number, percentage, country) VALUES (19,'Lusitania, Companhia de Seguros, S.A.', '913211910', '1.654194093', 'Portugal');
INSERT INTO medical_center.medical_center.insurance (company_id, company_name, phone_number, percentage, country) VALUES (20,'Mapfre Asistencia, Companhia Internacional de Seguros Y Reaseguros, S.A.', '912015672', '7.100730675', 'Espanha');
INSERT INTO medical_center.medical_center.insurance (company_id, company_name, phone_number, percentage, country) VALUES (21,'Mapfre Santander Portugal ? Companhia de Seguros, S.A.', '913395093', '9.980767056', 'Portugal');
INSERT INTO medical_center.medical_center.insurance (company_id, company_name, phone_number, percentage, country) VALUES (22,'Mapfre Seguros Gerais, S.A.', '913185152', '5.653276474', 'Portugal');
INSERT INTO medical_center.medical_center.insurance (company_id, company_name, phone_number, percentage, country) VALUES (23,'M�dis - Companhia Portuguesa de Seguros de Saude, S.A.', '914919779', '5.095991628', 'Portugal');
INSERT INTO medical_center.medical_center.insurance (company_id, company_name, phone_number, percentage, country) VALUES (24,'MetLife Europe d.a.c.', '919121150', '8.272687456', 'Irlanda');
INSERT INTO medical_center.medical_center.insurance (company_id, company_name, phone_number, percentage, country) VALUES (25,'MetLife Europe Insurance d.a.c.', '910888734', '3.053348812', 'Irlanda');
INSERT INTO medical_center.medical_center.insurance (company_id, company_name, phone_number, percentage, country) VALUES (26,'MUDUM - Companhia de Seguros, S.A.', '919080701', '3.037412', 'Portugal');
INSERT INTO medical_center.medical_center.insurance (company_id, company_name, phone_number, percentage, country) VALUES (27,'Multicare - Seguros de Saude, S.A.', '917423923', '1.665049974', 'Portugal');
INSERT INTO medical_center.medical_center.insurance (company_id, company_name, phone_number, percentage, country) VALUES (28,'Planicare - Companhia de Seguros, S.A.', '910200474', '3.52721941', 'Portugal');
INSERT INTO medical_center.medical_center.insurance (company_id, company_name, phone_number, percentage, country) VALUES (29,'Prevoir - Vie Groupe Prevoir S.A.', '912032885', '8.899107398', 'França');
INSERT INTO medical_center.medical_center.insurance (company_id, company_name, phone_number, percentage, country) VALUES (30,'Real Vida Seguros, S.A.', '914822682', '2.029311903', 'Portugal');
INSERT INTO medical_center.medical_center.insurance (company_id, company_name, phone_number, percentage, country) VALUES (31,'RNA Seguros, S.A.', '918938294', '3.031784575', 'Portugal');
INSERT INTO medical_center.medical_center.insurance (company_id, company_name, phone_number, percentage, country) VALUES (32,'Una Seguros, S.A.', '919773819', '8.9282653', 'Portugal');
INSERT INTO medical_center.medical_center.insurance (company_id, company_name, phone_number, percentage, country) VALUES (33,'Via Directa - Companhia de Seguros, S.A.', '913696697', '0.734140468', 'Portugal');
INSERT INTO medical_center.medical_center.insurance (company_id, company_name, phone_number, percentage, country) VALUES (34,'Victoria - Seguros, S.A.', '914438746', '4.217339183', 'Portugal');
INSERT INTO medical_center.medical_center.insurance (company_id, company_name, phone_number, percentage, country) VALUES (35,'Zurich Insurance PLC - Sucursal em Portugal', '913285477', '5.503807055', 'Irlanda');
